name: macOS

on:
    push:
        paths:
            - '**.cpp'
            - '**.h'

jobs:
    clang-release:
        runs-on: macos-latest
        env:
            targetName: RobotFrame
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
            version: 6.5.3
            cache: true
            cache-key-prefix: QtCache

        - name: Install brew and dependencies
          run: |
            brew install llvm
            brew install assimp
            brew install ompl
            brew install opencascade
            brew install orocos-kdl
            brew install mesa
            brew install spdlog
            brew install eigen
            brew install ninja
            brew install googletest
            brew install fmt
            brew install boost

        - name: Build Release
          working-directory: ${{github.workspace}}
          run: |
            export PATH="/usr/local/opt/llvm/bin:$PATH"
            cmake \
            -DCMAKE_BUILD_TYPE:STRING=Release \
            -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE \
            -DCMAKE_C_COMPILER:FILEPATH=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -B${{github.workspace}}/build/Mac_Ninja_Release \
            -S${{github.workspace}} -G Ninja
            cmake --build ${{github.workspace}}/build/Mac_Ninja_Release --config Release --target all --

        # CPU cost on mac is too expensive and the test errors are not able to reported. Forbid now.
        - name: Execute Unit Tests Release
          working-directory: ${{github.workspace}}/build/Mac_Ninja_Release
          run: |
            ctest -T test -j 3 --output-on-failure -E "UndoableObjectsTest.Concurrency"

